import type { AppType, CategoryType } from './types';

export const mockApps: AppType[] = [
  {
    _id: '1',
    name: 'purp - Make new friends',
    slug: 'com.hubolabs.hubo',
    developer: 'hubo Labs',
    developerWebsite: 'https://purp.social/',
    privacyPolicy: 'https://purp.social/privacy',
    icon: 'https://play-lh.googleusercontent.com/ZSDiLoqQ5S9mqgXIWRv_XJAN33ZwMFLXiK7BWPY9aK5RbzVM82YCLIMa8196a4WI1Rk=w240-h480-rw',
    screenshots: [
      'https://play-lh.googleusercontent.com/iUhTLN-ISXuLMbOJ6WJUbfWBACcLdrXC4lwa2NOsZFieYbpZ4vs3octN3_1mmx6cpA=w526-h296-rw',
      'https://play-lh.googleusercontent.com/sHVCJ_ozOHkwzQEiFwkgXug6YYaAo6acsMH8Ucp4cbXPyfbPaACINf1r_gXupEcQBaM=w526-h296-rw',
      'https://play-lh.googleusercontent.com/UNRliVMoanYxnVDgvo5wDJv0H0JmswxesCN1ZRrzIIV_SO96LufJ42Z3XZzcZdPFrp_X=w526-h296-rw',
    ],
    shortDescription: 'Swipe to make new friends! Discover new cultures and meet new people',
    fullDescription: `<p>purp is the best place to make new friends from all over the world! Discover new cultures, meet new people and start your own adventure. You asked how?! It's simple:</p><ol><li>swipe right to send a friend request</li><li>get notified when they accept your request,</li><li>you two can now chat and see each other socials!</li></ol><p><b>Express yourself</b></p><p>You can customize your profile by adding photos, videos, a unique bio or even going yolo and changing your profile colors!</p><p><b>Earn Gems</b></p><p>You need gems to send swipes. But they're super easy to earn:</p><ul><li>share purp with your friends</li><li>check-in every day</li><li>make new friends on purp!</li></ul>`,
    whatsNew: 'We\'ve squashed some bugs and made performance improvements to make your experience even better.',
    category: 'Social',
    tags: ['social', 'friends', 'chat', 'discover'],
    version: '4.4.3',
    fileSize: 58,
    minAndroidVersion: '7.0',
    downloads: 4294596,
    ratings: 100175,
    reviewsCount: 5302,
    averageRating: 4.4,
    histogram: [8583, 2365, 4440, 7645, 77125],
    reviews: [
      {
        id: '1',
        user: 'Landon',
        avatar: 'https://play-lh.googleusercontent.com/a-/ALV-UjUOKQpcrPdhUKMn8bsd3TTyuZx-KHFnUCw7NmxrlEk2nODtt1Iy',
        rating: 3,
        text: "I'm having my photos taken down for showing my shoulders. my LITERAL shoulders. if you consider teenagers' shoulders and collarbones sexual, that's creepy. also it says i get friend requests but they don't show up. otherwise, it's a nice app.",
        version: '4.4.1',
      },
       {
        id: '2',
        user: 'A Google User',
        avatar: '',
        rating: 5,
        text: "This app is amazing for making new friends! I've met so many cool people from different countries. The interface is super easy to use and fun.",
        version: '4.4.0',
      }
    ],
    contentRating: 'Teen',
    permissions: {
      "Photos/Media/Files": [
        "read the contents of your USB storage",
        "modify or delete the contents of your USB storage"
      ],
      "Camera": [
        "take pictures and videos"
      ]
    },
    dataSafety: [
        "This app may share these data types with third parties",
        "This app may collect these data types",
        "Data is encrypted in transit",
        "You can request that data be deleted"
    ],
    status: 'published',
    isFeatured: true,
    updatedAt: '2024-07-25',
  },
  {
    _id: '2',
    name: 'Nova Launcher Prime',
    slug: 'nova-launcher-prime',
    developer: 'TeslaCoil Software',
    developerWebsite: '#',
    privacyPolicy: '#',
    icon: 'https://picsum.photos/seed/appicon2/128/128',
    screenshots: [
      'https://picsum.photos/seed/ss2a/600/400',
      'https://picsum.photos/seed/ss2b/600/400',
    ],
    shortDescription: 'The highly customizable, performance driven, home screen.',
    fullDescription: '<p>Nova Launcher is the top launcher for modern Android, embracing full Material Design throughout. It replaces your home screen with one you control and can customize. Change icons, layouts, animations and more.</p>',
    whatsNew: 'v8.0.9: Added new search integrations and animation options.',
    category: 'Personalization',
    tags: ['launcher', 'customization', 'themes', 'home screen'],
    version: '8.0.9',
    fileSize: 12,
    minAndroidVersion: '8.0',
    downloads: 50000000,
    ratings: 1400000,
    reviewsCount: 80000,
    averageRating: 4.9,
    histogram: [1000, 500, 2500, 80000, 1316000],
    reviews: [],
    contentRating: 'Everyone',
    permissions: {},
    dataSafety: ["No data shared with third parties"],
    status: 'published',
    isFeatured: true,
    updatedAt: '2024-07-18',
  },
    {
    _id: '3',
    name: 'TaskMaster Pro',
    slug: 'taskmaster-pro',
    developer: 'Productivity Hub',
    developerWebsite: '#',
    privacyPolicy: '#',
    icon: 'https://picsum.photos/seed/appicon3/128/128',
    screenshots: [
      'https://picsum.photos/seed/ss3a/600/400',
      'https://picsum.photos/seed/ss3b/600/400',
      'https://picsum.photos/seed/ss3c/600/400',
    ],
    shortDescription: 'Organize your life and boost your productivity.',
    fullDescription: '<p>TaskMaster Pro helps you capture and organize tasks the moment they pop into your head. From small to-dos to big projects, TaskMaster has you covered with smart lists, reminders, and collaboration tools.</p>',
    whatsNew: 'v4.2.0: Introduced new calendar view and project templates.',
    category: 'Productivity',
    tags: ['todo', 'organizer', 'productivity', 'tasks'],
    version: '4.2.0',
    fileSize: 35,
    minAndroidVersion: '7.0',
    downloads: 850000,
    ratings: 45000,
    reviewsCount: 3000,
    averageRating: 4.7,
    histogram: [100, 200, 800, 10000, 33900],
    reviews: [],
    contentRating: 'Everyone',
    permissions: {},
    dataSafety: [],
    status: 'published',
    isFeatured: false,
    updatedAt: '2024-07-21',
  },
  {
    _id: '4',
    name: 'Galaxy Runner',
    slug: 'galaxy-runner',
    developer: 'Cosmic Games',
    developerWebsite: '#',
    privacyPolicy: '#',
    icon: 'https://picsum.photos/seed/appicon4/128/128',
    screenshots: [
        'https://picsum.photos/seed/ss4a/600/400',
        'https://picsum.photos/seed/ss4b/600/400',
    ],
    shortDescription: 'An endless runner set in a stunning sci-fi universe.',
    fullDescription: '<p>Dodge obstacles, collect power-ups, and challenge your friends in this fast-paced endless runner. With stunning graphics and addictive gameplay, Galaxy Runner will keep you on the edge of your seat.</p>',
    whatsNew: 'v1.9.3: New characters and power-ups added!',
    category: 'Games',
    tags: ['game', 'arcade', 'endless runner', 'sci-fi'],
    version: '1.9.3',
    fileSize: 150,
    minAndroidVersion: '5.1',
    downloads: 2300000,
    ratings: 95000,
    reviewsCount: 8000,
    averageRating: 4.5,
    histogram: [2000, 1500, 5000, 20000, 66500],
    reviews: [],
    contentRating: 'Everyone 10+',
    permissions: {},
    dataSafety: [],
    status: 'published',
    isFeatured: false,
    updatedAt: '2024-07-15',
  },
];

export const mockCategories: CategoryType[] = [
    { _id: '1', name: 'Games', slug: 'games', icon: 'gamepad', appsCount: 320 },
    { _id: '2', name: 'Tools', slug: 'tools', icon: 'wrench', appsCount: 450 },
    { _id: '3', name: 'Productivity', slug: 'productivity', icon: 'chart', appsCount: 210 },
    { _id: '4', name: 'Social', slug: 'social', icon: 'users', appsCount: 150 },
    { _id: '5', name: 'Photography', slug: 'photography', icon: 'camera', appsCount: 90 },
    { _id: '6', name: 'Personalization', slug: 'personalization', icon: 'palette', appsCount: 180 },
];
